# Generated by Django 4.2.1 on 2023-05-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_blogowner_remove_blog_github_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='areasDeInteresse',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='utilizador',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='autores',
            field=models.ManyToManyField(related_name='posts', to='portfolio.autor'),
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(related_name='posts', to='portfolio.comentario'),
        ),
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='areas',
            field=models.ManyToManyField(related_name='blogs', to='portfolio.area'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
