# Generated by Django 4.2.1 on 2023-05-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_autor_areasdeinteresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='posts',
        ),
        migrations.AddField(
            model_name='autor',
            name='areasDeInteresse',
            field=models.ManyToManyField(related_name='autores', to='portfolio.area'),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='portfolio.area'),
            preserve_default=False,
        ),
    ]
