# Generated by Django 4.2.1 on 2023-06-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_area_posts_autor_areasdeinteresse_post_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('anoLetivo', models.IntegerField()),
                ('professores', models.ManyToManyField(related_name='cadeiras', to='portfolio.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkLinkedin', models.URLField()),
                ('linkGithub', models.URLField()),
                ('nomeCidade', models.CharField(max_length=255)),
                ('linkFacebook', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('cadeiras', models.ManyToManyField(related_name='cursos', to='portfolio.cadeira')),
            ],
        ),
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100)),
                ('fotografia', models.ImageField(blank=True, upload_to='images/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkRepos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('linkGithub', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='noticiasPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricaoNoticia', models.CharField(max_length=400)),
                ('imagemNoticia', models.ImageField(upload_to='images/')),
                ('linkNoticia', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('linkPaginaLusofona', models.URLField(blank=True)),
                ('linkLinkedIn', models.URLField(blank=True)),
                ('linkAppPortfolio', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCompetencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anoDeRealizacao', models.IntegerField()),
                ('imagem', models.ImageField(upload_to='images/')),
                ('resumo', models.CharField(max_length=500)),
                ('linkRelatorio', models.URLField()),
                ('linkGithub', models.URLField(blank=True)),
                ('linkVideoYt', models.URLField(blank=True)),
                ('autores', models.ManyToManyField(to='portfolio.autor')),
                ('orientador', models.ManyToManyField(to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='TecnologiasPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('anoDeCriacao', models.IntegerField()),
                ('logotipo', models.ImageField(blank=True, upload_to='images/')),
                ('siteOficial', models.URLField()),
                ('linguagens', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=750)),
                ('criador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='sobreEsteWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapaDoSite', models.ImageField(upload_to='images/')),
                ('descricaoBD', models.CharField(max_length=244)),
                ('listaPadroesUsados', models.CharField(max_length=255)),
                ('comentarios', models.ManyToManyField(max_length=10, to='portfolio.comentario')),
                ('listaTecnologiasUsadas', models.ManyToManyField(to='portfolio.tecnologiaspw')),
            ],
        ),
        migrations.CreateModel(
            name='Rodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkGithub', models.URLField()),
                ('pythonAnywhere', models.URLField()),
                ('linkRepo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rodape', to='portfolio.linkrepos')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, upload_to='images/')),
                ('anoRealizacao', models.IntegerField()),
                ('linkGithub', models.URLField(blank=True, max_length=120)),
                ('videoYoutube', models.URLField(blank=True)),
                ('participantes', models.ManyToManyField(related_name='trabalhos', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='LaboratoriosPW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricaoTopicos', models.CharField(max_length=500)),
                ('linksRepos', models.ManyToManyField(to='portfolio.linkrepos')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
                ('imagemLogotipo', models.ImageField(blank=True, upload_to='images/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacoes', to='portfolio.cursomodelo')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('carga_horaria', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='portfolio.area')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projetosRealizados',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.projeto'),
        ),
        migrations.CreateModel(
            name='AptidoesCompetencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=100)),
                ('listaDisciplinas', models.ManyToManyField(related_name='aptidoesCompetencias', to='portfolio.cadeira')),
                ('listaProjetos', models.ManyToManyField(related_name='aptidoesCompetencias', to='portfolio.projeto')),
            ],
        ),
    ]
