# Generated by Django 4.2.1 on 2023-06-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_cadeira_contacto_cursomodelo_interesses_linkrepos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnologiaspw',
            name='criador',
        ),
        migrations.AddField(
            model_name='tecnologiaspw',
            name='criador',
            field=models.ManyToManyField(blank=True, related_name='tecnologias', to='portfolio.pessoa'),
        ),
    ]
