# Generated by Django 4.2.1 on 2023-06-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_tecnologiaspw_criador_tecnologiaspw_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='resumo',
            field=models.CharField(max_length=1000),
        ),
    ]
