# Generated by Django 4.2.1 on 2023-06-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_tfc_imagem_alter_tfc_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
