# Generated by Django 4.2.1 on 2023-06-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_tfc_imagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TFC',
            new_name='Tfcs',
        ),
    ]
