# Generated by Django 4.2.1 on 2023-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_educacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='professores',
            field=models.ManyToManyField(related_name='cadeiras', to='portfolio.pessoa'),
        ),
    ]
