# Generated by Django 4.2.1 on 2023-06-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_cadeira_professores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tfcs',
            new_name='TfcsInteresssantes',
        ),
    ]
