# Generated by Django 4.2.1 on 2023-06-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_tecnologiasexistentespw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sobreEsteWS',
            new_name='SobreWebsite',
        ),
    ]
