# Generated by Django 4.2.1 on 2023-06-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_padroesusados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padroesusados',
            old_name='logotipo',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='padroesusados',
            name='anoDeCriacao',
        ),
        migrations.RemoveField(
            model_name='padroesusados',
            name='criador',
        ),
        migrations.RemoveField(
            model_name='padroesusados',
            name='linguagens',
        ),
        migrations.RemoveField(
            model_name='padroesusados',
            name='siteOficial',
        ),
    ]
