# Generated by Django 4.2.1 on 2023-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_rename_logotipo_padroesusados_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnologiasexistentespw',
            name='descricao',
            field=models.CharField(max_length=1400),
        ),
    ]
