# Generated by Django 4.2.1 on 2023-06-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_professorv2_cadeirav2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TfcsInteresssantes',
            new_name='TfcsInteressantes',
        ),
    ]
