# Generated by Django 4.2.1 on 2023-06-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_weatherdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
